enabled: true
logo: logo.png
footer_icons:
  -
    icon: fa-facebook
    url: 'https://www.facebook.com/'
  -
    icon: 'fa fa-twitter'
    url: 'https://www.twitter.com/'
  -
    icon: fa-google-plus
    url: 'https://www.google.com/'
  -
    icon: fa-dribbble
    url: 'https://www.dribbble.com/'
footer_blocks:
  -
    content: 'Continually matrix cross functional opportunities whereas ethical information. Compellingly streamline enabled human capital before resource-leveling internal or "organic".'
    icons: false
  -
    title: 'We work for your profit'
    content: 'Distinctively expedite viral materials rather than out-of-the-box solutions. Credibly empower revolutionary ROI rather than unique products. Collaboratively maximize principle-centered ideas before highly efficient data. Phosfluorescently.'
    logo: false
    icons: false
  -
    title: 'Contact Us Today'
    content: "Call Us 666 777 888 OR 111 222 333\r\n\r\nSend an Email on <a href=\"mailto:#\">contact@domain.com</a>\r\n\r\nVisit Us 123 Fake Street- Blla 12358\r\nFake Kingdom"
    logo: false
copyright: 'Copyright &copy; 2016 | X-Corporation Designed And Developed By: <a href="http://www.uicookies.com">uiCookies</a>'
google_maps_api_key: AIzaSyDbmnZP5BTkpv5blTprRtUvS99zbvyoSAQ
